version: '3.8'

services:
  frontend:
    image: yunxizhang/dlt-demo-frontend-app:0.1
    container_name: dlt-demo-frontend-app
    volumes: 
      - ${PWD}/.env:/app/.env
    ports:
      - 3000:3000
    environment:
      - CI=true